### ISSUE TITLE
regarding gst results

### ISSUE THREAD

**Issue by vickyrev** [miccec/yaGST#1]
I run the method multiple times and I'm wondering why the NES value is always positive, regardless of the rank. According to the eeMWW scores, those genes that score closer to 1 could be considered "upregulated" whereas those closer to 0, "downregulated". However, even if I flip the values to run the pathway enrichment with mwwGST, I never obtain negative enrichment scores (and the results are quite different). I checked the supplemental information of the paper but I cannot find a plausible explanation for this.

**Comment by miccec** [comment]
Hello,
thanks for your interest. Yes NES here is always positive, the interval between 0-0.5 indicates negative enrichment whereas the interval 0.5-1 indicates positive enrichment. The NES is an estimate of the probability that the expression of a gene in the gene set is greater than the expression of a gene outside this set. The procedure also returns the variable "log.pu" which is equal to log2(NES/(1-NES)). You can interpret your results using log.pu and the p-value as well.
The value of log.pu will be negative if your gene set which is underrepresented in the top of the ranked list.

**Comment by vickyrev** [comment]
Thanks for the clarification!

**Comment by vickyrev** [comment]
Hi again! another related question.. I have tested it several times, and now considering that negative log2pu values would correspond to downregulated pathways, I notice that even obtaining similar abs(log2pu) values, the negatives always have very high pvalues (compared to pathways positively enriched, that are at the top with very low pvals). This happens every time, all negative pathways are at the bottom of the table when sorted by pval, even in tests with altered data. This seems to be correlated to lower NES values, although as stated before, NES is never below 0. I cannot seem to obtain significantly underrepresented (in the top of the ranked list) pathways.

**Comment by miccec** [comment]
Hello,
thanks for your support. Could you share your ranker list and the geneset you are using? We can  try  to have a look.

**Comment by vickyrev** [comment]
Sure! Thanks! Here I attach a txt file with a set of results:
[eeMWWresults.txt](https://github.com/miccec/yaGST/files/2150035/eeMWWresults.txt)
And this would be the GO BP enrichment. I sorted by qval, and as you can see, all negative enrichments are in the bottom, even with similar log2pu and sizes:
[GOBP_eeMWW_enrichment_results.xlsx](https://github.com/miccec/yaGST/files/2150043/GOBP_eeMWW_enrichment_results.xlsx)

It's an example: I've seen it with other runs of the software as well, and using other databases too.
